// ============================================================
// lang.js — Workshop 1 (Germania) · The European Union – a Journey through Time
// Lingue: en · it · pl · de · lv
// ============================================================

(function () {

  const TRANSLATIONS = {
    en: {
      skip_link: "Skip to content",
      btn_home_aria: "Back to Home",
      lang_switcher_aria: "Select language",
      flag_aria: "German flag",
      btn_top: "Top",
      btn_top_aria: "Back to top",
      hero_eyebrow: "Germany · Workshop 1",
      hero_title: "The European Union — a Journey through Time",
      page_title: "The European Union — a Journey through Time",
      hero_subtitle: "An interactive journey through the origins and development of the European Union, up to the present day — to feel part of the European community.",
      hero_authors: "Authors: <strong>Barbara Petersen, Renate Kronemann, Sabine Perisic, Achim Kolbe-Dierks</strong>",
      info_duration_label: "Duration",
      info_participants_label: "Participants",
      info_participants_value: "up to 19",
      hero_pill_audience_label: "Audience",
      info_audience_value: "Ages 50+",
      sec_about: "About the Workshop",
      about_text: "Participants expand their knowledge about the origins of the EU and its development up to today, and come to see themselves as part of the European community. The heart of the workshop is a timeline built together, step by step.",
      sec_objectives: "What the Workshop Develops",
      obj1: "Activate and recall existing knowledge about the EU.",
      obj2: "Place in chronological order the events that built European integration.",
      obj3: "Highlight the guiding principles of the European community.",
      obj4: "Deepen factual knowledge: treaties, accessions, dates.",
      obj5: "Reflect critically on the development of the EU and its consequences.",
      obj6: "Share personal experiences connected to the EU.",
      sec_agenda: "How the Workshop Unfolds (90 – 120 min)",
      ag1_title: "Warm-up round",
      ag1_text: "Each participant says one word they associate with the European idea.",
      ag2_title: "The milestones",
      ag2_text: "The eight key milestones are presented on a timeline laid out on the table.",
      ag3_title: "The 21 events",
      ag3_text: "In small groups, participants place 21 event cards in chronological order and present them.",
      ag4_title: "Memory games",
      ag4_text: "Memory games on the flags of EU countries and famous landmarks; the symbolism of the European flag is explained.",
      ag5_title: "Flags and accessions",
      ag5_text: "Country flags are placed on the timeline by their year of accession, with a discussion of the historical context.",
      ag6_title: "Final round",
      ag6_text: "Each participant shares what personal benefit they see in being an EU citizen.",
      sec_timeline: "The Timeline — milestones & events",
      timeline_lead: "From the Schuman Declaration to today. The <strong>milestones</strong> are highlighted; the other entries are the further events that shaped the Union.",
      tl_milestone: "Milestone",
      tl_event: "Event",
      ev1_t: "Schuman Declaration",
      ev1_d: "On 9 May, French Foreign Minister Robert Schuman proposes the creation of the ECSC. Today this day is celebrated as Europe Day.",
      ev2_t: "European Court of Justice",
      ev2_d: "The Court of Justice of the European Union, based in Luxembourg, is established.",
      ev3_t: "Treaty of Paris",
      ev3_d: "The European Coal and Steel Community (ECSC), also known as the 'Montanunion', enters into force.",
      ev4_t: "Treaties of Rome",
      ev4_d: "The treaties establishing the European Economic Community (EEC) and Euratom enter into force.",
      ev5_t: "Merger Treaty",
      ev5_d: "The ECSC, EEC and Euratom merge into the European Communities (EC).",
      ev6_t: "European Political Cooperation",
      ev6_d: "EC countries set up European Political Cooperation (EPC) to better represent their foreign-policy interests.",
      ev7_t: "European Elections",
      ev7_d: "The first direct elections to the European Parliament are introduced.",
      ev8_t: "Greenland",
      ev8_d: "After a referendum, Greenland withdraws from the EC but remains associated with it.",
      ev9_t: "Europe's Flag and Anthem",
      ev9_d: "The European flag is hoisted for the first time and the 'Ode to Joy' becomes the European anthem.",
      ev10_t: "Erasmus",
      ev10_d: "The Erasmus programme is launched.",
      ev11_t: "Single European Act",
      ev11_d: "The Single European Act enters into force, aiming to complete the internal market by 1 January 1993.",
      ev12_t: "EU Ecolabel",
      ev12_d: "The EU Ecolabel — the 'Euroflower' — becomes the official environmental label of the EU.",
      ev13_t: "Treaty of Maastricht",
      ev13_d: "The European Union (EU) is created, merging the EEC, ECSC and Euratom, with cooperation in foreign, defence, police and justice policy.",
      ev14_t: "Schengen Agreement",
      ev14_d: "The agreement abolishing checks on persons at the EU's internal borders enters into force.",
      ev15_t: "European Central Bank",
      ev15_d: "The ECB is founded in Frankfurt, tasked with ensuring price stability in the euro area.",
      ev16_t: "Europol",
      ev16_d: "Europol, the European Police Office, is founded in The Hague to fight serious crime and terrorism.",
      ev17_t: "Euro — Virtual Currency",
      ev17_d: "The euro is introduced as a virtual currency unit, replacing the ECU.",
      ev18_t: "Charter of Fundamental Rights",
      ev18_d: "The Charter of Fundamental Rights of the European Union is adopted.",
      ev19_t: "Motto 'United in Diversity'",
      ev19_d: "The Commission chooses 'United in Diversity' as the motto of the EU.",
      ev20_t: "AGE Platform Europe",
      ev20_d: "The European umbrella organisation representing the interests of older people is founded.",
      ev21_t: "Introduction of Euro Cash",
      ev21_d: "The euro becomes the official cash currency in 12 EU countries.",
      ev22_t: "Treaty of Nice",
      ev22_d: "The Treaty of Nice strengthens the European Parliament and sets institutional reforms in motion.",
      ev23_t: "Treaty of Lisbon",
      ev23_d: "The structure and working methods of the EU are reformed; it is the EU's current treaty basis.",
      ev24_t: "Euro Sovereign Debt Crisis",
      ev24_d: "High public debt and falling tax revenues push some EU countries towards bankruptcy.",
      ev25_t: "EU Recovery Package",
      ev25_d: "Financially threatened member states are supported through the euro rescue package.",
      ev26_t: "Nobel Peace Prize",
      ev26_d: "The EU is awarded the Nobel Peace Prize for advancing peace, reconciliation, democracy and human rights.",
      ev27_t: "Peak of the Refugee Crisis",
      ev27_d: "In a short time over a million people reach Europe; the countries on the EU's external borders are overwhelmed.",
      ev28_t: "Brexit",
      ev28_d: "After a 2016 referendum and years of negotiation, the United Kingdom leaves the EU, which now has 27 members.",
      ev29_t: "Corona Pandemic",
      ev29_d: "Health systems are overburdened; lockdowns put the economy and social life into crisis.",
      sec_accessions: "The Countries Join — Enlargements",
      acc_lead: "From the six founding countries to today's 27 member states.",
      acc1_t: "Founding Countries",
      acc1_c: "Belgium, Germany, France, Italy, Luxembourg, Netherlands",
      acc2_t: "First Enlargement",
      acc2_c: "Denmark, Ireland, United Kingdom",
      acc3_t: "Enlargement to the South",
      acc3_c: "Greece",
      acc4_t: "Second Southern Enlargement",
      acc4_c: "Portugal, Spain",
      acc5_t: "EFTA Enlargement",
      acc5_c: "Finland, Austria, Sweden",
      acc6_t: "Major Eastern Enlargement",
      acc6_c: "Estonia, Latvia, Lithuania, Malta, Poland, Slovakia, Slovenia, Czech Republic, Hungary, Cyprus",
      acc7_t: "Enlargement",
      acc7_c: "Bulgaria, Romania",
      acc8_t: "Latest Enlargement",
      acc8_c: "Croatia",
      sec_whoiswho: "Who is Who?",
      wiw_lead: "Three names that are easy to confuse.",
      wiw1_t: "Council of Europe",
      wiw1_d: "An international organisation (not an EU institution), based in Strasbourg, devoted to human rights, democracy and the rule of law.",
      wiw2_t: "European Council",
      wiw2_d: "Defines the EU's general objectives and priorities. Members: the heads of state or government, plus the Presidents of the European Council and the Commission.",
      wiw3_t: "Council of the European Union",
      wiw3_d: "Negotiates and adopts EU legislation (usually together with the Parliament). Members: the relevant ministers of the member states.",
      sec_downloads: "Materials to Download & Games",
      dl_lead: "All the materials from the German workshop, ready to print. For each item, use the buttons to download the PDF in German (DE) or English (EN).",
      dl_g_guide: "For facilitators",
      dl_g_activity: "Timeline activity (to print & cut out)",
      dl_g_games: "Memory games",
      dl_g_visual: "Illustrative materials",
      dl_script: "Workshop script (guide)",
      dl_timeline: "Ready-made timeline",
      dl_eventcards: "21 event cards (detailed)",
      dl_eventcards_task: "Event cards without year (the task)",
      dl_chronology: "Chronology (answer key)",
      dl_milestones: "8 milestone cards",
      dl_flags: "Country flags & accessions",
      dl_memory_flags: "Memory — EU flags",
      dl_memory_landmarks: "Memory — landmarks",
      dl_map: "Map of EU countries",
      dl_institutions: "EU institutions diagram",
      dl_whoiswho: "Who is Who (definitions)",
      dl_script_d: "Step-by-step guide for whoever leads the workshop.",
      dl_timeline_d: "The complete timeline, ready to print as a poster.",
      dl_eventcards_d: "One card per event, with the year and a full explanation.",
      dl_eventcards_task_d: "The same events without the year: participants put them in order.",
      dl_chronology_d: "The correct order of the events — for the facilitator to check.",
      dl_milestones_d: "The 8 most important steps, to introduce the timeline.",
      dl_flags_d: "Country flags to place on the timeline by year of accession.",
      dl_memory_flags_d: "Card game to learn the flags of the EU countries.",
      dl_memory_landmarks_d: "Card game on famous European landmarks.",
      dl_map_d: "Map of Europe showing the EU member countries.",
      dl_institutions_d: "A simple diagram of how the EU institutions fit together.",
      dl_whoiswho_d: "Clears up three names that are easy to confuse.",
      dl_note: "Note: the files are the German team's originals, so they exist only in German (DE) and English (EN). The page itself is translated into all languages.",
      footer_text: "Erasmus+ Project · Workshop 1 (Germany) — The European Union: a Journey through Time",
      footer_credit: "LUTE MILAZZO web project — by Filippo Russo Nuccio",
    },
    it: {
      skip_link: "Salta al contenuto",
      btn_home_aria: "Torna alla Home",
      lang_switcher_aria: "Seleziona lingua",
      flag_aria: "Bandiera tedesca",
      btn_top: "Su",
      btn_top_aria: "Torna in alto",
      hero_eyebrow: "Germania · Workshop 1",
      hero_title: "L'Unione Europea — un viaggio nel tempo",
      page_title: "L'Unione Europea — un viaggio nel tempo",
      hero_subtitle: "Un viaggio interattivo nelle origini e nello sviluppo dell'Unione Europea, fino a oggi — per sentirsi parte della comunità europea.",
      hero_authors: "Autori: <strong>Barbara Petersen, Renate Kronemann, Sabine Perisic, Achim Kolbe-Dierks</strong>",
      info_duration_label: "Durata",
      info_participants_label: "Partecipanti",
      info_participants_value: "fino a 19",
      hero_pill_audience_label: "Pubblico",
      info_audience_value: "Over 50",
      sec_about: "Presentazione",
      about_text: "I partecipanti ampliano la conoscenza delle origini dell'UE e del suo sviluppo fino a oggi, e arrivano a sentirsi parte della comunità europea. Il cuore del laboratorio è una linea del tempo costruita insieme, passo dopo passo.",
      sec_objectives: "Cosa sviluppa il laboratorio",
      obj1: "Attivare e richiamare le conoscenze già possedute sull'UE.",
      obj2: "Mettere in ordine cronologico gli eventi che hanno costruito l'integrazione europea.",
      obj3: "Mettere in luce i principi guida della comunità europea.",
      obj4: "Approfondire le conoscenze fattuali: trattati, adesioni, date.",
      obj5: "Riflettere criticamente sullo sviluppo dell'UE e sulle sue conseguenze.",
      obj6: "Condividere esperienze personali legate all'UE.",
      sec_agenda: "Come si svolge il laboratorio (90 – 120 min)",
      ag1_title: "Giro di riscaldamento",
      ag1_text: "Ogni partecipante dice una parola che associa all'idea europea.",
      ag2_title: "Le tappe fondamentali",
      ag2_text: "Le otto tappe fondamentali vengono presentate su una linea del tempo disposta sul tavolo.",
      ag3_title: "I 21 eventi",
      ag3_text: "In piccoli gruppi, i partecipanti dispongono 21 carte-evento in ordine cronologico e le presentano.",
      ag4_title: "Giochi di memory",
      ag4_text: "Giochi di memory sulle bandiere dei Paesi UE e sui monumenti famosi; si spiega il simbolismo della bandiera europea.",
      ag5_title: "Bandiere e adesioni",
      ag5_text: "Le bandiere dei Paesi vengono collocate sulla linea del tempo in base all'anno di adesione, con una discussione sul contesto storico.",
      ag6_title: "Giro finale",
      ag6_text: "Ogni partecipante racconta quale beneficio personale vede nell'essere cittadino dell'UE.",
      sec_timeline: "La linea del tempo — tappe ed eventi",
      timeline_lead: "Dalla Dichiarazione Schuman a oggi. Le <strong>tappe fondamentali</strong> sono evidenziate; le altre voci sono gli ulteriori eventi che hanno plasmato l'Unione.",
      tl_milestone: "Tappa fondamentale",
      tl_event: "Evento",
      ev1_t: "Dichiarazione Schuman",
      ev1_d: "Il 9 maggio il ministro degli Esteri francese Robert Schuman propone la creazione della CECA. Oggi questa data è celebrata come la Festa dell'Europa.",
      ev2_t: "Corte di Giustizia europea",
      ev2_d: "Viene istituita la Corte di Giustizia dell'Unione Europea, con sede in Lussemburgo.",
      ev3_t: "Trattato di Parigi",
      ev3_d: "Entra in vigore la Comunità Europea del Carbone e dell'Acciaio (CECA), nota anche come 'Montanunion'.",
      ev4_t: "Trattati di Roma",
      ev4_d: "Entrano in vigore i trattati che istituiscono la Comunità Economica Europea (CEE) e l'Euratom.",
      ev5_t: "Trattato di fusione",
      ev5_d: "La CECA, la CEE e l'Euratom si fondono nelle Comunità Europee (CE).",
      ev6_t: "Cooperazione politica europea",
      ev6_d: "I Paesi della CE istituiscono la Cooperazione Politica Europea (CPE) per rappresentare meglio i propri interessi di politica estera.",
      ev7_t: "Elezioni europee",
      ev7_d: "Vengono introdotte le prime elezioni dirette del Parlamento Europeo.",
      ev8_t: "Groenlandia",
      ev8_d: "Dopo un referendum, la Groenlandia esce dalla CE ma resta a essa associata.",
      ev9_t: "Bandiera e inno europei",
      ev9_d: "La bandiera europea viene issata per la prima volta e l'«Inno alla gioia» diventa l'inno europeo.",
      ev10_t: "Erasmus",
      ev10_d: "Viene lanciato il programma Erasmus.",
      ev11_t: "Atto unico europeo",
      ev11_d: "Entra in vigore l'Atto unico europeo, con l'obiettivo di completare il mercato interno entro il 1° gennaio 1993.",
      ev12_t: "Ecolabel UE",
      ev12_d: "L'Ecolabel UE — il «fiore europeo» — diventa il marchio ambientale ufficiale dell'UE.",
      ev13_t: "Trattato di Maastricht",
      ev13_d: "Nasce l'Unione Europea (UE), che unisce CEE, CECA ed Euratom, con cooperazione in politica estera, difesa, polizia e giustizia.",
      ev14_t: "Accordo di Schengen",
      ev14_d: "Entra in vigore l'accordo che abolisce i controlli sulle persone alle frontiere interne dell'UE.",
      ev15_t: "Banca Centrale Europea",
      ev15_d: "Viene fondata la BCE a Francoforte, con il compito di garantire la stabilità dei prezzi nell'area euro.",
      ev16_t: "Europol",
      ev16_d: "Viene fondato Europol, l'Ufficio europeo di polizia, all'Aia, per combattere la criminalità grave e il terrorismo.",
      ev17_t: "Euro — moneta virtuale",
      ev17_d: "L'euro viene introdotto come unità di conto virtuale, sostituendo l'ECU.",
      ev18_t: "Carta dei diritti fondamentali",
      ev18_d: "Viene adottata la Carta dei diritti fondamentali dell'Unione Europea.",
      ev19_t: "Motto «Unita nella diversità»",
      ev19_d: "La Commissione sceglie «Unita nella diversità» come motto dell'UE.",
      ev20_t: "AGE Platform Europe",
      ev20_d: "Viene fondata l'organizzazione europea che rappresenta gli interessi delle persone anziane.",
      ev21_t: "Introduzione dell'euro in contanti",
      ev21_d: "L'euro diventa la moneta contante ufficiale in 12 Paesi dell'UE.",
      ev22_t: "Trattato di Nizza",
      ev22_d: "Il Trattato di Nizza rafforza il Parlamento Europeo e avvia riforme istituzionali.",
      ev23_t: "Trattato di Lisbona",
      ev23_d: "La struttura e i metodi di lavoro dell'UE vengono riformati; è l'attuale base giuridica dell'UE.",
      ev24_t: "Crisi del debito sovrano",
      ev24_d: "L'alto debito pubblico e il calo delle entrate fiscali spingono alcuni Paesi UE verso il fallimento.",
      ev25_t: "Pacchetto di salvataggio UE",
      ev25_d: "Gli Stati membri in difficoltà finanziaria vengono sostenuti tramite il pacchetto di salvataggio dell'euro.",
      ev26_t: "Premio Nobel per la Pace",
      ev26_d: "All'UE viene assegnato il Premio Nobel per la Pace per aver promosso pace, riconciliazione, democrazia e diritti umani.",
      ev27_t: "Picco della crisi dei rifugiati",
      ev27_d: "In poco tempo oltre un milione di persone raggiunge l'Europa; i Paesi alle frontiere esterne dell'UE sono sovraccarichi.",
      ev28_t: "Brexit",
      ev28_d: "Dopo il referendum del 2016 e anni di negoziati, il Regno Unito lascia l'UE, che ora conta 27 membri.",
      ev29_t: "Pandemia di Covid",
      ev29_d: "I sistemi sanitari sono sovraccarichi; i lockdown mettono in crisi l'economia e la vita sociale.",
      sec_accessions: "L'ingresso dei Paesi — gli allargamenti",
      acc_lead: "Dai sei Paesi fondatori agli attuali 27 Stati membri.",
      acc1_t: "Paesi fondatori",
      acc1_c: "Belgio, Germania, Francia, Italia, Lussemburgo, Paesi Bassi",
      acc2_t: "Primo allargamento",
      acc2_c: "Danimarca, Irlanda, Regno Unito",
      acc3_t: "Allargamento a Sud",
      acc3_c: "Grecia",
      acc4_t: "Secondo allargamento a Sud",
      acc4_c: "Portogallo, Spagna",
      acc5_t: "Allargamento EFTA",
      acc5_c: "Finlandia, Austria, Svezia",
      acc6_t: "Grande allargamento a Est",
      acc6_c: "Estonia, Lettonia, Lituania, Malta, Polonia, Slovacchia, Slovenia, Repubblica Ceca, Ungheria, Cipro",
      acc7_t: "Allargamento",
      acc7_c: "Bulgaria, Romania",
      acc8_t: "Ultimo allargamento",
      acc8_c: "Croazia",
      sec_whoiswho: "Chi è chi?",
      wiw_lead: "Tre nomi facili da confondere.",
      wiw1_t: "Consiglio d'Europa",
      wiw1_d: "Un'organizzazione internazionale (non un'istituzione dell'UE), con sede a Strasburgo, dedicata ai diritti umani, alla democrazia e allo Stato di diritto.",
      wiw2_t: "Consiglio europeo",
      wiw2_d: "Definisce gli obiettivi generali e le priorità dell'UE. Membri: i capi di Stato o di governo, più i Presidenti del Consiglio europeo e della Commissione.",
      wiw3_t: "Consiglio dell'Unione Europea",
      wiw3_d: "Negozia e adotta la legislazione dell'UE (di solito insieme al Parlamento). Membri: i ministri competenti degli Stati membri.",
      sec_downloads: "Materiali da scaricare e giochi",
      dl_lead: "Tutti i materiali del laboratorio tedesco, pronti da stampare. Per ogni voce, usa i pulsanti per scaricare il PDF in tedesco (DE) o in inglese (EN).",
      dl_g_guide: "Per i conduttori",
      dl_g_activity: "Attività linea del tempo (da stampare e ritagliare)",
      dl_g_games: "Giochi di memory",
      dl_g_visual: "Materiali illustrativi",
      dl_script: "Script del laboratorio (guida)",
      dl_timeline: "Linea del tempo già composta",
      dl_eventcards: "21 carte-evento (dettagliate)",
      dl_eventcards_task: "Carte-evento senza anno (il compito)",
      dl_chronology: "Cronologia (soluzione)",
      dl_milestones: "8 carte delle tappe fondamentali",
      dl_flags: "Bandiere dei Paesi e adesioni",
      dl_memory_flags: "Memory — bandiere UE",
      dl_memory_landmarks: "Memory — monumenti",
      dl_map: "Mappa dei Paesi UE",
      dl_institutions: "Schema delle istituzioni UE",
      dl_whoiswho: "Chi è chi (definizioni)",
      dl_script_d: "Guida passo-passo per chi conduce il laboratorio.",
      dl_timeline_d: "La linea del tempo completa, da stampare come cartellone.",
      dl_eventcards_d: "Una carta per evento, con l'anno e la spiegazione completa.",
      dl_eventcards_task_d: "Gli stessi eventi senza l'anno: i partecipanti li mettono in ordine.",
      dl_chronology_d: "L'ordine corretto degli eventi — per la verifica del conduttore.",
      dl_milestones_d: "Le 8 tappe più importanti, per introdurre la linea del tempo.",
      dl_flags_d: "Le bandiere dei Paesi da collocare sulla linea del tempo per anno di adesione.",
      dl_memory_flags_d: "Gioco di carte per imparare le bandiere dei Paesi UE.",
      dl_memory_landmarks_d: "Gioco di carte sui monumenti europei famosi.",
      dl_map_d: "Mappa dell'Europa con i Paesi membri dell'UE.",
      dl_institutions_d: "Uno schema semplice di come si collegano le istituzioni dell'UE.",
      dl_whoiswho_d: "Chiarisce tre nomi facili da confondere.",
      dl_note: "Nota: i file sono gli originali del team tedesco, quindi esistono solo in tedesco (DE) e inglese (EN). La pagina, invece, è tradotta in tutte le lingue.",
      footer_text: "Progetto Erasmus+ · Workshop 1 (Germania) — L'Unione Europea: un viaggio nel tempo",
      footer_credit: "Progetto web LUTE MILAZZO — curato da Filippo Russo Nuccio",
    },
    pl: {
      skip_link: "Przejdź do treści",
      btn_home_aria: "Powrót do strony głównej",
      lang_switcher_aria: "Wybierz język",
      flag_aria: "Flaga Niemiec",
      btn_top: "Góra",
      btn_top_aria: "Powrót na górę",
      hero_eyebrow: "Niemcy · Warsztat 1",
      hero_title: "Unia Europejska — podróż w czasie",
      page_title: "Unia Europejska — podróż w czasie",
      hero_subtitle: "Interaktywna podróż przez początki i rozwój Unii Europejskiej aż do dziś — aby poczuć się częścią wspólnoty europejskiej.",
      hero_authors: "Autorzy: <strong>Barbara Petersen, Renate Kronemann, Sabine Perisic, Achim Kolbe-Dierks</strong>",
      info_duration_label: "Czas trwania",
      info_participants_label: "Uczestnicy",
      info_participants_value: "do 19",
      hero_pill_audience_label: "Odbiorcy",
      info_audience_value: "50+",
      sec_about: "O warsztacie",
      about_text: "Uczestnicy poszerzają wiedzę o początkach UE i jej rozwoju aż do dziś oraz zaczynają postrzegać siebie jako część wspólnoty europejskiej. Sercem warsztatu jest oś czasu budowana wspólnie, krok po kroku.",
      sec_objectives: "Czego rozwija warsztat",
      obj1: "Aktywować i przypomnieć posiadaną wiedzę o UE.",
      obj2: "Uporządkować chronologicznie wydarzenia, które zbudowały integrację europejską.",
      obj3: "Podkreślić zasady przewodnie wspólnoty europejskiej.",
      obj4: "Pogłębić wiedzę faktograficzną: traktaty, przystąpienia, daty.",
      obj5: "Krytycznie zastanowić się nad rozwojem UE i jego konsekwencjami.",
      obj6: "Podzielić się osobistymi doświadczeniami związanymi z UE.",
      sec_agenda: "Jak przebiega warsztat (90 – 120 min)",
      ag1_title: "Runda na rozgrzewkę",
      ag1_text: "Każdy uczestnik podaje jedno słowo kojarzące mu się z ideą europejską.",
      ag2_title: "Kamienie milowe",
      ag2_text: "Osiem kluczowych kamieni milowych przedstawia się na osi czasu rozłożonej na stole.",
      ag3_title: "21 wydarzeń",
      ag3_text: "W małych grupach uczestnicy układają 21 kart wydarzeń w porządku chronologicznym i je prezentują.",
      ag4_title: "Gry memory",
      ag4_text: "Gry memory z flagami państw UE i słynnymi zabytkami; wyjaśniana jest symbolika flagi europejskiej.",
      ag5_title: "Flagi i przystąpienia",
      ag5_text: "Flagi państw umieszcza się na osi czasu według roku przystąpienia, z omówieniem kontekstu historycznego.",
      ag6_title: "Runda końcowa",
      ag6_text: "Każdy uczestnik mówi, jaką osobistą korzyść widzi w byciu obywatelem UE.",
      sec_timeline: "Oś czasu — kamienie milowe i wydarzenia",
      timeline_lead: "Od deklaracji Schumana do dziś. <strong>Kamienie milowe</strong> są wyróżnione; pozostałe wpisy to kolejne wydarzenia, które ukształtowały Unię.",
      tl_milestone: "Kamień milowy",
      tl_event: "Wydarzenie",
      ev1_t: "Deklaracja Schumana",
      ev1_d: "9 maja francuski minister spraw zagranicznych Robert Schuman proponuje utworzenie EWWiS. Dziś ten dzień obchodzony jest jako Dzień Europy.",
      ev2_t: "Trybunał Sprawiedliwości UE",
      ev2_d: "Powstaje Trybunał Sprawiedliwości Unii Europejskiej z siedzibą w Luksemburgu.",
      ev3_t: "Traktat paryski",
      ev3_d: "Wchodzi w życie Europejska Wspólnota Węgla i Stali (EWWiS), znana też jako 'Montanunion'.",
      ev4_t: "Traktaty rzymskie",
      ev4_d: "Wchodzą w życie traktaty ustanawiające Europejską Wspólnotę Gospodarczą (EWG) i Euratom.",
      ev5_t: "Traktat fuzyjny",
      ev5_d: "EWWiS, EWG i Euratom łączą się we Wspólnoty Europejskie (WE).",
      ev6_t: "Europejska Współpraca Polityczna",
      ev6_d: "Państwa WE tworzą Europejską Współpracę Polityczną (EWP), aby lepiej reprezentować swoje interesy w polityce zagranicznej.",
      ev7_t: "Wybory europejskie",
      ev7_d: "Wprowadza się pierwsze bezpośrednie wybory do Parlamentu Europejskiego.",
      ev8_t: "Grenlandia",
      ev8_d: "Po referendum Grenlandia występuje z WE, ale pozostaje z nią stowarzyszona.",
      ev9_t: "Flaga i hymn Europy",
      ev9_d: "Po raz pierwszy podniesiona zostaje flaga europejska, a 'Oda do radości' staje się hymnem Europy.",
      ev10_t: "Erasmus",
      ev10_d: "Uruchomiony zostaje program Erasmus.",
      ev11_t: "Jednolity akt europejski",
      ev11_d: "Wchodzi w życie Jednolity akt europejski, którego celem jest ukończenie rynku wewnętrznego do 1 stycznia 1993 r.",
      ev12_t: "Oznakowanie ekologiczne UE",
      ev12_d: "Oznakowanie ekologiczne UE — 'Euro-stokrotka' — staje się oficjalnym znakiem środowiskowym UE.",
      ev13_t: "Traktat z Maastricht",
      ev13_d: "Powstaje Unia Europejska (UE), łącząc EWG, EWWiS i Euratom, ze współpracą w polityce zagranicznej, obronie, policji i sprawiedliwości.",
      ev14_t: "Układ z Schengen",
      ev14_d: "Wchodzi w życie układ znoszący kontrolę osób na granicach wewnętrznych UE.",
      ev15_t: "Europejski Bank Centralny",
      ev15_d: "Powstaje EBC z siedzibą we Frankfurcie, którego zadaniem jest zapewnienie stabilności cen w strefie euro.",
      ev16_t: "Europol",
      ev16_d: "W Hadze powstaje Europol, Europejski Urząd Policji, do walki z poważną przestępczością i terroryzmem.",
      ev17_t: "Euro — waluta wirtualna",
      ev17_d: "Euro zostaje wprowadzone jako wirtualna jednostka walutowa, zastępując ECU.",
      ev18_t: "Karta praw podstawowych",
      ev18_d: "Zostaje przyjęta Karta praw podstawowych Unii Europejskiej.",
      ev19_t: "Motto 'Zjednoczona w różnorodności'",
      ev19_d: "Komisja wybiera 'Zjednoczona w różnorodności' jako motto UE.",
      ev20_t: "AGE Platform Europe",
      ev20_d: "Powstaje europejska organizacja parasolowa reprezentująca interesy osób starszych.",
      ev21_t: "Wprowadzenie gotówki euro",
      ev21_d: "Euro staje się oficjalną walutą gotówkową w 12 krajach UE.",
      ev22_t: "Traktat nicejski",
      ev22_d: "Traktat nicejski wzmacnia Parlament Europejski i uruchamia reformy instytucjonalne.",
      ev23_t: "Traktat lizboński",
      ev23_d: "Reformowane są struktura i metody pracy UE; to obecna podstawa traktatowa UE.",
      ev24_t: "Kryzys zadłużeniowy strefy euro",
      ev24_d: "Wysokie zadłużenie publiczne i spadek wpływów podatkowych pchają niektóre kraje UE ku bankructwu.",
      ev25_t: "Pakiet ratunkowy UE",
      ev25_d: "Państwa członkowskie zagrożone finansowo są wspierane poprzez pakiet ratunkowy euro.",
      ev26_t: "Pokojowa Nagroda Nobla",
      ev26_d: "UE otrzymuje Pokojową Nagrodę Nobla za szerzenie pokoju, pojednania, demokracji i praw człowieka.",
      ev27_t: "Szczyt kryzysu uchodźczego",
      ev27_d: "W krótkim czasie do Europy dociera ponad milion osób; kraje na zewnętrznych granicach UE są przeciążone.",
      ev28_t: "Brexit",
      ev28_d: "Po referendum z 2016 r. i latach negocjacji Wielka Brytania opuszcza UE, która liczy teraz 27 członków.",
      ev29_t: "Pandemia koronawirusa",
      ev29_d: "Systemy ochrony zdrowia są przeciążone; lockdowny pogrążają w kryzysie gospodarkę i życie społeczne.",
      sec_accessions: "Przystąpienia państw — rozszerzenia",
      acc_lead: "Od sześciu krajów założycielskich do dzisiejszych 27 państw członkowskich.",
      acc1_t: "Kraje założycielskie",
      acc1_c: "Belgia, Niemcy, Francja, Włochy, Luksemburg, Holandia",
      acc2_t: "Pierwsze rozszerzenie",
      acc2_c: "Dania, Irlandia, Wielka Brytania",
      acc3_t: "Rozszerzenie na południe",
      acc3_c: "Grecja",
      acc4_t: "Drugie rozszerzenie na południe",
      acc4_c: "Portugalia, Hiszpania",
      acc5_t: "Rozszerzenie o EFTA",
      acc5_c: "Finlandia, Austria, Szwecja",
      acc6_t: "Wielkie rozszerzenie na wschód",
      acc6_c: "Estonia, Łotwa, Litwa, Malta, Polska, Słowacja, Słowenia, Czechy, Węgry, Cypr",
      acc7_t: "Rozszerzenie",
      acc7_c: "Bułgaria, Rumunia",
      acc8_t: "Ostatnie rozszerzenie",
      acc8_c: "Chorwacja",
      sec_whoiswho: "Kto jest kim?",
      wiw_lead: "Trzy nazwy, które łatwo pomylić.",
      wiw1_t: "Rada Europy",
      wiw1_d: "Organizacja międzynarodowa (nie instytucja UE) z siedzibą w Strasburgu, poświęcona prawom człowieka, demokracji i praworządności.",
      wiw2_t: "Rada Europejska",
      wiw2_d: "Określa ogólne cele i priorytety UE. Członkowie: szefowie państw lub rządów oraz przewodniczący Rady Europejskiej i Komisji.",
      wiw3_t: "Rada Unii Europejskiej",
      wiw3_d: "Negocjuje i przyjmuje prawodawstwo UE (zwykle wspólnie z Parlamentem). Członkowie: właściwi ministrowie państw członkowskich.",
      sec_downloads: "Materiały do pobrania i gry",
      dl_lead: "Wszystkie materiały z niemieckiego warsztatu, gotowe do druku. Przy każdej pozycji użyj przycisków, aby pobrać PDF po niemiecku (DE) lub angielsku (EN).",
      dl_g_guide: "Dla prowadzących",
      dl_g_activity: "Aktywność oś czasu (do druku i wycięcia)",
      dl_g_games: "Gry memory",
      dl_g_visual: "Materiały ilustracyjne",
      dl_script: "Scenariusz warsztatu (przewodnik)",
      dl_timeline: "Gotowa oś czasu",
      dl_eventcards: "21 kart wydarzeń (szczegółowe)",
      dl_eventcards_task: "Karty wydarzeń bez roku (zadanie)",
      dl_chronology: "Chronologia (klucz odpowiedzi)",
      dl_milestones: "8 kart kamieni milowych",
      dl_flags: "Flagi państw i przystąpienia",
      dl_memory_flags: "Memory — flagi UE",
      dl_memory_landmarks: "Memory — zabytki",
      dl_map: "Mapa państw UE",
      dl_institutions: "Schemat instytucji UE",
      dl_whoiswho: "Kto jest kim (definicje)",
      dl_script_d: "Przewodnik krok po kroku dla osoby prowadzącej warsztat.",
      dl_timeline_d: "Kompletna oś czasu, gotowa do druku jako plakat.",
      dl_eventcards_d: "Jedna karta na wydarzenie, z rokiem i pełnym wyjaśnieniem.",
      dl_eventcards_task_d: "Te same wydarzenia bez roku: uczestnicy układają je w kolejności.",
      dl_chronology_d: "Poprawna kolejność wydarzeń — do sprawdzenia przez prowadzącego.",
      dl_milestones_d: "8 najważniejszych etapów, do wprowadzenia osi czasu.",
      dl_flags_d: "Flagi państw do umieszczenia na osi czasu według roku przystąpienia.",
      dl_memory_flags_d: "Gra karciana do nauki flag państw UE.",
      dl_memory_landmarks_d: "Gra karciana o słynnych europejskich zabytkach.",
      dl_map_d: "Mapa Europy z państwami członkowskimi UE.",
      dl_institutions_d: "Prosty schemat powiązań instytucji UE.",
      dl_whoiswho_d: "Wyjaśnia trzy łatwe do pomylenia nazwy.",
      dl_note: "Uwaga: pliki to oryginały zespołu niemieckiego, dlatego istnieją tylko po niemiecku (DE) i angielsku (EN). Sama strona jest przetłumaczona na wszystkie języki.",
      footer_text: "Projekt Erasmus+ · Warsztat 1 (Niemcy) — Unia Europejska: podróż w czasie",
      footer_credit: "Projekt strony LUTE MILAZZO — wykonał Filippo Russo Nuccio",
    },
    de: {
      skip_link: "Zum Inhalt springen",
      btn_home_aria: "Zurück zur Startseite",
      lang_switcher_aria: "Sprache wählen",
      flag_aria: "Deutsche Flagge",
      btn_top: "Nach oben",
      btn_top_aria: "Nach oben",
      hero_eyebrow: "Deutschland · Workshop 1",
      hero_title: "Die Europäische Union — eine Reise durch die Zeit",
      page_title: "Die Europäische Union — eine Reise durch die Zeit",
      hero_subtitle: "Eine interaktive Reise durch die Ursprünge und die Entwicklung der Europäischen Union bis heute — um sich als Teil der europäischen Gemeinschaft zu fühlen.",
      hero_authors: "Autoren: <strong>Barbara Petersen, Renate Kronemann, Sabine Perisic, Achim Kolbe-Dierks</strong>",
      info_duration_label: "Dauer",
      info_participants_label: "Teilnehmer",
      info_participants_value: "bis zu 19",
      hero_pill_audience_label: "Zielgruppe",
      info_audience_value: "Ab 50 Jahren",
      sec_about: "Über den Workshop",
      about_text: "Die Teilnehmenden erweitern ihr Wissen über die Ursprünge der EU und ihre Entwicklung bis heute und verstehen sich als Teil der europäischen Gemeinschaft. Herzstück des Workshops ist eine gemeinsam, Schritt für Schritt erstellte Zeitleiste.",
      sec_objectives: "Was der Workshop fördert",
      obj1: "Vorhandenes Wissen über die EU aktivieren und abrufen.",
      obj2: "Die Ereignisse der europäischen Integration chronologisch einordnen.",
      obj3: "Die Leitprinzipien der europäischen Gemeinschaft hervorheben.",
      obj4: "Faktenwissen vertiefen: Verträge, Beitritte, Daten.",
      obj5: "Kritisch über die Entwicklung der EU und ihre Folgen nachdenken.",
      obj6: "Persönliche Erfahrungen mit Bezug zur EU einbringen.",
      sec_agenda: "Ablauf des Workshops (90 – 120 Min.)",
      ag1_title: "Aufwärmrunde",
      ag1_text: "Jede teilnehmende Person nennt ein Wort, das sie mit der europäischen Idee verbindet.",
      ag2_title: "Die Meilensteine",
      ag2_text: "Die acht wichtigsten Meilensteine werden auf einer Zeitleiste auf dem Tisch vorgestellt.",
      ag3_title: "Die 21 Ereignisse",
      ag3_text: "In Kleingruppen ordnen die Teilnehmenden 21 Ereigniskarten chronologisch und stellen sie vor.",
      ag4_title: "Memory-Spiele",
      ag4_text: "Memory-Spiele zu den Flaggen der EU-Länder und bekannten Wahrzeichen; die Symbolik der Europaflagge wird erklärt.",
      ag5_title: "Flaggen und Beitritte",
      ag5_text: "Die Länderflaggen werden nach ihrem Beitrittsjahr auf der Zeitleiste platziert, mit einer Diskussion des historischen Kontexts.",
      ag6_title: "Abschlussrunde",
      ag6_text: "Jede teilnehmende Person teilt mit, welchen persönlichen Nutzen sie als EU-Bürger sieht.",
      sec_timeline: "Die Zeitleiste — Meilensteine & Ereignisse",
      timeline_lead: "Von der Schuman-Erklärung bis heute. Die <strong>Meilensteine</strong> sind hervorgehoben; die übrigen Einträge sind die weiteren Ereignisse, die die Union geprägt haben.",
      tl_milestone: "Meilenstein",
      tl_event: "Ereignis",
      ev1_t: "Schuman-Erklärung",
      ev1_d: "Am 9. Mai schlägt der französische Außenminister Robert Schuman die Gründung der EGKS vor. Dieser Tag wird heute als Europatag gefeiert.",
      ev2_t: "Europäischer Gerichtshof",
      ev2_d: "Der Gerichtshof der Europäischen Union mit Sitz in Luxemburg wird gegründet.",
      ev3_t: "Vertrag von Paris",
      ev3_d: "Die Europäische Gemeinschaft für Kohle und Stahl (EGKS), auch 'Montanunion' genannt, tritt in Kraft.",
      ev4_t: "Römische Verträge",
      ev4_d: "Die Verträge zur Gründung der Europäischen Wirtschaftsgemeinschaft (EWG) und von Euratom treten in Kraft.",
      ev5_t: "Fusionsvertrag",
      ev5_d: "EGKS, EWG und Euratom werden zu den Europäischen Gemeinschaften (EG) zusammengeführt.",
      ev6_t: "Europäische Politische Zusammenarbeit",
      ev6_d: "Die EG-Länder gründen die Europäische Politische Zusammenarbeit (EPZ), um ihre außenpolitischen Interessen besser zu vertreten.",
      ev7_t: "Europawahlen",
      ev7_d: "Die ersten Direktwahlen zum Europäischen Parlament werden eingeführt.",
      ev8_t: "Grönland",
      ev8_d: "Nach einem Referendum tritt Grönland aus der EG aus, bleibt ihr aber assoziiert.",
      ev9_t: "Europas Flagge und Hymne",
      ev9_d: "Die Europaflagge wird zum ersten Mal gehisst und die 'Ode an die Freude' wird zur Europahymne.",
      ev10_t: "Erasmus",
      ev10_d: "Das Erasmus-Programm wird ins Leben gerufen.",
      ev11_t: "Einheitliche Europäische Akte",
      ev11_d: "Die Einheitliche Europäische Akte tritt in Kraft mit dem Ziel, den Binnenmarkt bis zum 1. Januar 1993 zu vollenden.",
      ev12_t: "EU-Umweltzeichen",
      ev12_d: "Das EU-Umweltzeichen — die 'Euroblume' — wird zum offiziellen Umweltsiegel der EU.",
      ev13_t: "Vertrag von Maastricht",
      ev13_d: "Die Europäische Union (EU) entsteht durch Zusammenführung von EWG, EGKS und Euratom, mit Zusammenarbeit in Außen-, Verteidigungs-, Polizei- und Justizpolitik.",
      ev14_t: "Schengener Abkommen",
      ev14_d: "Das Abkommen zur Abschaffung der Personenkontrollen an den EU-Binnengrenzen tritt in Kraft.",
      ev15_t: "Europäische Zentralbank",
      ev15_d: "Die EZB wird in Frankfurt gegründet, mit der Aufgabe, die Preisstabilität im Euroraum zu sichern.",
      ev16_t: "Europol",
      ev16_d: "Europol, das Europäische Polizeiamt, wird in Den Haag gegründet, um schwere Kriminalität und Terrorismus zu bekämpfen.",
      ev17_t: "Euro — virtuelle Währung",
      ev17_d: "Der Euro wird als virtuelle Währungseinheit eingeführt und ersetzt den ECU.",
      ev18_t: "Charta der Grundrechte",
      ev18_d: "Die Charta der Grundrechte der Europäischen Union wird angenommen.",
      ev19_t: "Motto 'In Vielfalt geeint'",
      ev19_d: "Die Kommission wählt 'In Vielfalt geeint' als Motto der EU.",
      ev20_t: "AGE Platform Europe",
      ev20_d: "Die europäische Dachorganisation zur Vertretung der Interessen älterer Menschen wird gegründet.",
      ev21_t: "Einführung des Euro-Bargelds",
      ev21_d: "Der Euro wird in 12 EU-Ländern zum offiziellen Bargeld.",
      ev22_t: "Vertrag von Nizza",
      ev22_d: "Der Vertrag von Nizza stärkt das Europäische Parlament und setzt institutionelle Reformen in Gang.",
      ev23_t: "Vertrag von Lissabon",
      ev23_d: "Struktur und Arbeitsweise der EU werden reformiert; er ist die heutige Vertragsgrundlage der EU.",
      ev24_t: "Euro-Staatsschuldenkrise",
      ev24_d: "Hohe Staatsverschuldung und sinkende Steuereinnahmen treiben einige EU-Länder an den Rand der Pleite.",
      ev25_t: "EU-Rettungspaket",
      ev25_d: "Finanziell bedrohte Mitgliedstaaten werden durch das Euro-Rettungspaket unterstützt.",
      ev26_t: "Friedensnobelpreis",
      ev26_d: "Die EU erhält den Friedensnobelpreis für die Förderung von Frieden, Versöhnung, Demokratie und Menschenrechten.",
      ev27_t: "Höhepunkt der Flüchtlingskrise",
      ev27_d: "In kurzer Zeit erreichen über eine Million Menschen Europa; die Länder an den EU-Außengrenzen sind überfordert.",
      ev28_t: "Brexit",
      ev28_d: "Nach einem Referendum 2016 und jahrelangen Verhandlungen verlässt das Vereinigte Königreich die EU, die nun 27 Mitglieder hat.",
      ev29_t: "Corona-Pandemie",
      ev29_d: "Die Gesundheitssysteme sind überlastet; Lockdowns stürzen Wirtschaft und gesellschaftliches Leben in die Krise.",
      sec_accessions: "Die Länder treten bei — die Erweiterungen",
      acc_lead: "Von den sechs Gründungsländern zu den heutigen 27 Mitgliedstaaten.",
      acc1_t: "Gründungsländer",
      acc1_c: "Belgien, Deutschland, Frankreich, Italien, Luxemburg, Niederlande",
      acc2_t: "Erste Erweiterung",
      acc2_c: "Dänemark, Irland, Vereinigtes Königreich",
      acc3_t: "Erweiterung nach Süden",
      acc3_c: "Griechenland",
      acc4_t: "Zweite Süderweiterung",
      acc4_c: "Portugal, Spanien",
      acc5_t: "EFTA-Erweiterung",
      acc5_c: "Finnland, Österreich, Schweden",
      acc6_t: "Große Osterweiterung",
      acc6_c: "Estland, Lettland, Litauen, Malta, Polen, Slowakei, Slowenien, Tschechien, Ungarn, Zypern",
      acc7_t: "Erweiterung",
      acc7_c: "Bulgarien, Rumänien",
      acc8_t: "Jüngste Erweiterung",
      acc8_c: "Kroatien",
      sec_whoiswho: "Wer ist wer?",
      wiw_lead: "Drei leicht zu verwechselnde Namen.",
      wiw1_t: "Europarat",
      wiw1_d: "Eine internationale Organisation (keine EU-Institution) mit Sitz in Straßburg, die sich Menschenrechten, Demokratie und Rechtsstaatlichkeit widmet.",
      wiw2_t: "Europäischer Rat",
      wiw2_d: "Legt die allgemeinen Ziele und Prioritäten der EU fest. Mitglieder: die Staats- und Regierungschefs sowie die Präsidenten des Europäischen Rates und der Kommission.",
      wiw3_t: "Rat der Europäischen Union",
      wiw3_d: "Verhandelt und beschließt EU-Rechtsvorschriften (meist gemeinsam mit dem Parlament). Mitglieder: die zuständigen Minister der Mitgliedstaaten.",
      sec_downloads: "Materialien zum Herunterladen & Spiele",
      dl_lead: "Alle Materialien des deutschen Workshops, druckfertig. Bei jedem Eintrag laden Sie das PDF über die Schaltflächen auf Deutsch (DE) oder Englisch (EN) herunter.",
      dl_g_guide: "Für die Moderation",
      dl_g_activity: "Zeitleisten-Aktivität (zum Ausdrucken & Ausschneiden)",
      dl_g_games: "Memory-Spiele",
      dl_g_visual: "Anschauungsmaterial",
      dl_script: "Workshop-Skript (Leitfaden)",
      dl_timeline: "Fertige Zeitleiste",
      dl_eventcards: "21 Ereigniskarten (ausführlich)",
      dl_eventcards_task: "Ereigniskarten ohne Jahr (die Aufgabe)",
      dl_chronology: "Chronologie (Lösung)",
      dl_milestones: "8 Meilenstein-Karten",
      dl_flags: "Länderflaggen & Beitritte",
      dl_memory_flags: "Memory — EU-Flaggen",
      dl_memory_landmarks: "Memory — Wahrzeichen",
      dl_map: "Karte der EU-Länder",
      dl_institutions: "Schema der EU-Institutionen",
      dl_whoiswho: "Wer ist wer (Definitionen)",
      dl_script_d: "Schritt-für-Schritt-Anleitung für die Workshop-Leitung.",
      dl_timeline_d: "Die komplette Zeitleiste, druckfertig als Poster.",
      dl_eventcards_d: "Eine Karte pro Ereignis, mit Jahr und ausführlicher Erklärung.",
      dl_eventcards_task_d: "Dieselben Ereignisse ohne Jahr: Die Teilnehmenden ordnen sie.",
      dl_chronology_d: "Die richtige Reihenfolge der Ereignisse — zur Kontrolle für die Leitung.",
      dl_milestones_d: "Die 8 wichtigsten Schritte, zur Einführung der Zeitleiste.",
      dl_flags_d: "Länderflaggen, die nach Beitrittsjahr auf der Zeitleiste platziert werden.",
      dl_memory_flags_d: "Kartenspiel zum Lernen der Flaggen der EU-Länder.",
      dl_memory_landmarks_d: "Kartenspiel zu bekannten europäischen Wahrzeichen.",
      dl_map_d: "Europakarte mit den EU-Mitgliedsländern.",
      dl_institutions_d: "Ein einfaches Schema, wie die EU-Institutionen zusammenhängen.",
      dl_whoiswho_d: "Klärt drei leicht zu verwechselnde Namen.",
      dl_note: "Hinweis: Die Dateien sind die Originale des deutschen Teams und liegen daher nur auf Deutsch (DE) und Englisch (EN) vor. Die Seite selbst ist in alle Sprachen übersetzt.",
      footer_text: "Erasmus+-Projekt · Workshop 1 (Deutschland) — Die Europäische Union: eine Reise durch die Zeit",
      footer_credit: "LUTE MILAZZO-Webprojekt — von Filippo Russo Nuccio",
    },
    lv: {
      skip_link: "Pāriet uz saturu",
      btn_home_aria: "Atpakaļ uz sākumlapu",
      lang_switcher_aria: "Izvēlēties valodu",
      flag_aria: "Vācijas karogs",
      btn_top: "Uz augšu",
      btn_top_aria: "Uz augšu",
      hero_eyebrow: "Vācija · 1. seminārs",
      hero_title: "Eiropas Savienība — ceļojums laikā",
      page_title: "Eiropas Savienība — ceļojums laikā",
      hero_subtitle: "Interaktīvs ceļojums Eiropas Savienības pirmsākumos un attīstībā līdz mūsdienām — lai justos kā daļa no Eiropas kopienas.",
      hero_authors: "Autori: <strong>Barbara Petersen, Renate Kronemann, Sabine Perisic, Achim Kolbe-Dierks</strong>",
      info_duration_label: "Ilgums",
      info_participants_label: "Dalībnieki",
      info_participants_value: "līdz 19",
      hero_pill_audience_label: "Auditorija",
      info_audience_value: "50+",
      sec_about: "Par semināru",
      about_text: "Dalībnieki paplašina zināšanas par ES pirmsākumiem un attīstību līdz mūsdienām un sāk sevi uztvert kā daļu no Eiropas kopienas. Semināra centrā ir kopīgi, soli pa solim veidota laika līnija.",
      sec_objectives: "Ko seminārs attīsta",
      obj1: "Aktivizēt un atsaukt atmiņā esošās zināšanas par ES.",
      obj2: "Hronoloģiskā secībā sakārtot notikumus, kas veidoja Eiropas integrāciju.",
      obj3: "Izcelt Eiropas kopienas vadošos principus.",
      obj4: "Padziļināt faktu zināšanas: līgumi, pievienošanās, datumi.",
      obj5: "Kritiski pārdomāt ES attīstību un tās sekas.",
      obj6: "Dalīties personīgajā pieredzē saistībā ar ES.",
      sec_agenda: "Kā norisinās seminārs (90 – 120 min)",
      ag1_title: "Iesildīšanās aplis",
      ag1_text: "Katrs dalībnieks nosauc vienu vārdu, ko saista ar Eiropas ideju.",
      ag2_title: "Pagrieziena punkti",
      ag2_text: "Astoņi galvenie pagrieziena punkti tiek parādīti uz galda izklātā laika līnijā.",
      ag3_title: "21 notikumi",
      ag3_text: "Mazās grupās dalībnieki sakārto 21 notikumu kartiņu hronoloģiskā secībā un tās prezentē.",
      ag4_title: "Atmiņas spēles",
      ag4_text: "Atmiņas spēles ar ES valstu karogiem un slaveniem objektiem; tiek izskaidrota Eiropas karoga simbolika.",
      ag5_title: "Karogi un pievienošanās",
      ag5_text: "Valstu karogi tiek izvietoti laika līnijā pēc pievienošanās gada, apspriežot vēsturisko kontekstu.",
      ag6_title: "Noslēguma aplis",
      ag6_text: "Katrs dalībnieks pastāsta, kādu personīgu labumu saskata, būdams ES pilsonis.",
      sec_timeline: "Laika līnija — pagrieziena punkti un notikumi",
      timeline_lead: "No Šūmaņa deklarācijas līdz mūsdienām. <strong>Pagrieziena punkti</strong> ir izcelti; pārējie ieraksti ir citi notikumi, kas veidoja Savienību.",
      tl_milestone: "Pagrieziena punkts",
      tl_event: "Notikums",
      ev1_t: "Šūmaņa deklarācija",
      ev1_d: "9. maijā Francijas ārlietu ministrs Robērs Šūmans ierosina izveidot EOTK. Šodien šī diena tiek atzīmēta kā Eiropas diena.",
      ev2_t: "Eiropas Savienības Tiesa",
      ev2_d: "Tiek izveidota Eiropas Savienības Tiesa ar mītni Luksemburgā.",
      ev3_t: "Parīzes līgums",
      ev3_d: "Stājas spēkā Eiropas Ogļu un tērauda kopiena (EOTK), kas pazīstama arī kā 'Montanunion'.",
      ev4_t: "Romas līgumi",
      ev4_d: "Stājas spēkā līgumi, ar kuriem izveido Eiropas Ekonomikas kopienu (EEK) un Euratom.",
      ev5_t: "Apvienošanās līgums",
      ev5_d: "EOTK, EEK un Euratom apvienojas Eiropas Kopienās (EK).",
      ev6_t: "Eiropas politiskā sadarbība",
      ev6_d: "EK valstis izveido Eiropas politisko sadarbību (EPS), lai labāk pārstāvētu savas ārpolitikas intereses.",
      ev7_t: "Eiropas vēlēšanas",
      ev7_d: "Tiek ieviestas pirmās tiešās Eiropas Parlamenta vēlēšanas.",
      ev8_t: "Grenlande",
      ev8_d: "Pēc referenduma Grenlande izstājas no EK, taču paliek ar to asociēta.",
      ev9_t: "Eiropas karogs un himna",
      ev9_d: "Pirmo reizi tiek pacelts Eiropas karogs, un 'Oda priekam' kļūst par Eiropas himnu.",
      ev10_t: "Erasmus",
      ev10_d: "Tiek uzsākta programma Erasmus.",
      ev11_t: "Vienotais Eiropas akts",
      ev11_d: "Stājas spēkā Vienotais Eiropas akts, kura mērķis ir pabeigt iekšējo tirgu līdz 1993. gada 1. janvārim.",
      ev12_t: "ES ekomarķējums",
      ev12_d: "ES ekomarķējums — 'Eiropas puķe' — kļūst par ES oficiālo vides marķējumu.",
      ev13_t: "Māstrihtas līgums",
      ev13_d: "Tiek izveidota Eiropas Savienība (ES), apvienojot EEK, EOTK un Euratom, ar sadarbību ārlietu, aizsardzības, policijas un tieslietu jomā.",
      ev14_t: "Šengenas līgums",
      ev14_d: "Stājas spēkā līgums, ar ko atceļ personu kontroli pie ES iekšējām robežām.",
      ev15_t: "Eiropas Centrālā banka",
      ev15_d: "Frankfurtē tiek dibināta ECB, kuras uzdevums ir nodrošināt cenu stabilitāti eiro zonā.",
      ev16_t: "Eiropols",
      ev16_d: "Hāgā tiek dibināts Eiropols, Eiropas Policijas birojs, lai apkarotu smagu noziedzību un terorismu.",
      ev17_t: "Eiro — virtuālā valūta",
      ev17_d: "Eiro tiek ieviests kā virtuāla valūtas vienība, aizstājot ECU.",
      ev18_t: "Pamattiesību harta",
      ev18_d: "Tiek pieņemta Eiropas Savienības Pamattiesību harta.",
      ev19_t: "Devīze 'Vienoti dažādībā'",
      ev19_d: "Komisija izvēlas 'Vienoti dažādībā' par ES devīzi.",
      ev20_t: "AGE Platform Europe",
      ev20_d: "Tiek dibināta Eiropas jumta organizācija, kas pārstāv vecāka gadagājuma cilvēku intereses.",
      ev21_t: "Eiro skaidrās naudas ieviešana",
      ev21_d: "Eiro kļūst par oficiālo skaidrās naudas valūtu 12 ES valstīs.",
      ev22_t: "Nicas līgums",
      ev22_d: "Nicas līgums stiprina Eiropas Parlamentu un uzsāk institucionālās reformas.",
      ev23_t: "Lisabonas līgums",
      ev23_d: "Tiek reformēta ES struktūra un darba metodes; tas ir pašreizējais ES līgumiskais pamats.",
      ev24_t: "Eiro valstu parādu krīze",
      ev24_d: "Augstais valsts parāds un nodokļu ieņēmumu kritums dažas ES valstis tuvina bankrotam.",
      ev25_t: "ES glābšanas pakete",
      ev25_d: "Finansiāli apdraudētās dalībvalstis tiek atbalstītas ar eiro glābšanas paketi.",
      ev26_t: "Nobela Miera prēmija",
      ev26_d: "ES tiek piešķirta Nobela Miera prēmija par miera, izlīguma, demokrātijas un cilvēktiesību veicināšanu.",
      ev27_t: "Bēgļu krīzes kulminācija",
      ev27_d: "Īsā laikā Eiropu sasniedz vairāk nekā miljons cilvēku; valstis pie ES ārējām robežām ir pārslogotas.",
      ev28_t: "Brexit",
      ev28_d: "Pēc 2016. gada referenduma un gadiem ilgām sarunām Apvienotā Karaliste pamet ES, kurā tagad ir 27 dalībvalstis.",
      ev29_t: "Covid pandēmija",
      ev29_d: "Veselības aprūpes sistēmas ir pārslogotas; ierobežojumi iegrūž krīzē ekonomiku un sabiedrisko dzīvi.",
      sec_accessions: "Valstu pievienošanās — paplašināšanās",
      acc_lead: "No sešām dibinātājvalstīm līdz mūsdienu 27 dalībvalstīm.",
      acc1_t: "Dibinātājvalstis",
      acc1_c: "Beļģija, Vācija, Francija, Itālija, Luksemburga, Nīderlande",
      acc2_t: "Pirmā paplašināšanās",
      acc2_c: "Dānija, Īrija, Apvienotā Karaliste",
      acc3_t: "Paplašināšanās uz dienvidiem",
      acc3_c: "Grieķija",
      acc4_t: "Otrā dienvidu paplašināšanās",
      acc4_c: "Portugāle, Spānija",
      acc5_t: "EBTA paplašināšanās",
      acc5_c: "Somija, Austrija, Zviedrija",
      acc6_t: "Lielā austrumu paplašināšanās",
      acc6_c: "Igaunija, Latvija, Lietuva, Malta, Polija, Slovākija, Slovēnija, Čehija, Ungārija, Kipra",
      acc7_t: "Paplašināšanās",
      acc7_c: "Bulgārija, Rumānija",
      acc8_t: "Jaunākā paplašināšanās",
      acc8_c: "Horvātija",
      sec_whoiswho: "Kas ir kas?",
      wiw_lead: "Trīs viegli sajaucami nosaukumi.",
      wiw1_t: "Eiropas Padome",
      wiw1_d: "Starptautiska organizācija (nevis ES iestāde) ar mītni Strasbūrā, kas veltīta cilvēktiesībām, demokrātijai un tiesiskumam.",
      wiw2_t: "Eiropadome",
      wiw2_d: "Nosaka ES vispārējos mērķus un prioritātes. Locekļi: valstu vai valdību vadītāji un Eiropadomes un Komisijas priekšsēdētāji.",
      wiw3_t: "Eiropas Savienības Padome",
      wiw3_d: "Apspriež un pieņem ES tiesību aktus (parasti kopā ar Parlamentu). Locekļi: dalībvalstu attiecīgie ministri.",
      sec_downloads: "Lejupielādējamie materiāli un spēles",
      dl_lead: "Visi vācu semināra materiāli, gatavi drukāšanai. Katram ierakstam izmantojiet pogas, lai lejupielādētu PDF vāciski (DE) vai angliski (EN).",
      dl_g_guide: "Vadītājiem",
      dl_g_activity: "Laika līnijas aktivitāte (drukāšanai un izgriešanai)",
      dl_g_games: "Atmiņas spēles",
      dl_g_visual: "Uzskates materiāli",
      dl_script: "Semināra scenārijs (rokasgrāmata)",
      dl_timeline: "Gatava laika līnija",
      dl_eventcards: "21 notikumu kartiņas (detalizētas)",
      dl_eventcards_task: "Notikumu kartiņas bez gada (uzdevums)",
      dl_chronology: "Hronoloģija (atbilžu atslēga)",
      dl_milestones: "8 pagrieziena punktu kartiņas",
      dl_flags: "Valstu karogi un pievienošanās",
      dl_memory_flags: "Atmiņas spēle — ES karogi",
      dl_memory_landmarks: "Atmiņas spēle — objekti",
      dl_map: "ES valstu karte",
      dl_institutions: "ES iestāžu shēma",
      dl_whoiswho: "Kas ir kas (definīcijas)",
      dl_script_d: "Soli pa solim ceļvedis semināra vadītājam.",
      dl_timeline_d: "Pilna laika līnija, gatava drukāšanai kā plakāts.",
      dl_eventcards_d: "Viena kartiņa katram notikumam, ar gadu un pilnu skaidrojumu.",
      dl_eventcards_task_d: "Tie paši notikumi bez gada: dalībnieki tos sakārto secībā.",
      dl_chronology_d: "Pareizā notikumu secība — vadītāja pārbaudei.",
      dl_milestones_d: "8 svarīgākie posmi, lai ieviestu laika līniju.",
      dl_flags_d: "Valstu karogi, ko izvietot laika līnijā pēc pievienošanās gada.",
      dl_memory_flags_d: "Kāršu spēle, lai apgūtu ES valstu karogus.",
      dl_memory_landmarks_d: "Kāršu spēle par slaveniem Eiropas objektiem.",
      dl_map_d: "Eiropas karte ar ES dalībvalstīm.",
      dl_institutions_d: "Vienkārša shēma, kā ES iestādes ir saistītas.",
      dl_whoiswho_d: "Izskaidro trīs viegli sajaucamus nosaukumus.",
      dl_note: "Piezīme: faili ir vācu komandas oriģināli, tāpēc tie pieejami tikai vāciski (DE) un angliski (EN). Pati lapa ir tulkota visās valodās.",
      footer_text: "Erasmus+ projekts · 1. seminārs (Vācija) — Eiropas Savienība: ceļojums laikā",
      footer_credit: "LUTE MILAZZO tīmekļa projekts — veidoja Filippo Russo Nuccio",
    },
  };

  var LANGS = {
    en: {
      label: 'English',
      svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 36"><rect width="60" height="36" fill="#012169"/><path d="M0,0 L60,36 M60,0 L0,36" stroke="#fff" stroke-width="12"/><path d="M0,0 L60,36 M60,0 L0,36" stroke="#C8102E" stroke-width="4"/><rect x="0" y="13.5" width="60" height="9" fill="#fff"/><rect x="25.5" y="0" width="9" height="36" fill="#fff"/><rect x="0" y="15" width="60" height="6" fill="#C8102E"/><rect x="27" y="0" width="6" height="36" fill="#C8102E"/></svg>'
    },
    it: {
      label: 'Italiano',
      svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 30 20"><rect width="10" height="20" fill="#009246"/><rect x="10" width="10" height="20" fill="#fff"/><rect x="20" width="10" height="20" fill="#CE2B37"/></svg>'
    },
    pl: {
      label: 'Polski',
      svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 30 20"><rect width="30" height="10" fill="#fff"/><rect y="10" width="30" height="10" fill="#DC143C"/></svg>'
    },
    de: {
      label: 'Deutsch',
      svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 30 20"><rect width="30" height="6.67" fill="#000"/><rect y="6.67" width="30" height="6.67" fill="#DD0000"/><rect y="13.33" width="30" height="6.67" fill="#FFCE00"/></svg>'
    },
    lv: {
      label: 'Latvie\u0161u',
      svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 30 20"><rect width="30" height="8" fill="#9E3039"/><rect y="8" width="30" height="4" fill="#fff"/><rect y="12" width="30" height="8" fill="#9E3039"/></svg>'
    }
  };

  var currentLang = localStorage.getItem('erasmus_lang') || 'en';

  function apply(lang) {
    var t = TRANSLATIONS[lang];
    if (!t) return;

    // Testo semplice
    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      var key = el.getAttribute('data-i18n');
      if (t[key] !== undefined) el.textContent = t[key];
    });

    // Testo con HTML interno (grassetto, corsivo…)
    document.querySelectorAll('[data-i18n-html]').forEach(function (el) {
      var key = el.getAttribute('data-i18n-html');
      if (t[key] !== undefined) el.innerHTML = t[key];
    });

    // aria-label dinamici
    document.querySelectorAll('[data-i18n-aria]').forEach(function (el) {
      var key = el.getAttribute('data-i18n-aria');
      if (t[key] !== undefined) el.setAttribute('aria-label', t[key]);
    });

    // Titolo pagina
    if (t.page_title) document.title = t.page_title;

    // Attributo lang sull'HTML
    document.documentElement.setAttribute('lang', lang);

    // Stato pulsanti desktop
    document.querySelectorAll('.lang-btn').forEach(function (btn) {
      var active = btn.getAttribute('data-lang') === lang;
      btn.classList.toggle('lang-btn--active', active);
      btn.setAttribute('aria-pressed', active ? 'true' : 'false');
    });

    // Pulsante mobile: aggiorna bandiera e stato voci dropdown
    var switcher = document.getElementById('langSwitcher');
    if (switcher && switcher._mobileFlag) {
      switcher._mobileFlag.src = 'data:image/svg+xml,' + encodeURIComponent(LANGS[lang].svg);
      switcher._mobileFlag.alt = LANGS[lang].label;
    }
    if (switcher && switcher._dropdown) {
      switcher._dropdown.querySelectorAll('[data-lang-item]').forEach(function (item) {
        item.classList.toggle('lang-dropdown-item--active',
          item.getAttribute('data-lang-item') === lang);
      });
    }

    currentLang = lang;
    localStorage.setItem('erasmus_lang', lang);
  }

  function makeFlagImg(code, w, h) {
    var img = document.createElement('img');
    img.src = 'data:image/svg+xml,' + encodeURIComponent(LANGS[code].svg);
    img.alt = LANGS[code].label;
    img.setAttribute('width', String(w));
    img.setAttribute('height', String(h));
    img.style.cssText = 'border-radius:2px;box-shadow:0 0 0 1px rgba(0,0,0,0.15);display:block;flex-shrink:0;';
    return img;
  }

  function buildSwitcher() {
    var switcher = document.getElementById('langSwitcher');
    if (!switcher) return;

    // ---- DESKTOP: una bandierina per ogni lingua ----
    Object.keys(LANGS).forEach(function (code) {
      var btn = document.createElement('button');
      btn.className = 'lang-btn';
      btn.setAttribute('data-lang', code);
      btn.setAttribute('aria-label', LANGS[code].label);
      btn.setAttribute('aria-pressed', 'false');
      btn.setAttribute('type', 'button');
      btn.appendChild(makeFlagImg(code, 32, 22));
      btn.addEventListener('click', function () { apply(code); });
      switcher.appendChild(btn);
    });

    // ---- MOBILE: pulsante singolo + menu a discesa ----
    var mobileBtn = document.createElement('button');
    mobileBtn.className = 'lang-mobile-btn';
    mobileBtn.id = 'langMobileBtn';
    mobileBtn.setAttribute('type', 'button');
    mobileBtn.setAttribute('aria-haspopup', 'true');
    mobileBtn.setAttribute('aria-expanded', 'false');
    mobileBtn.setAttribute('aria-label', 'Seleziona lingua');

    var mobileFlag = document.createElement('img');
    mobileFlag.setAttribute('width', '32');
    mobileFlag.setAttribute('height', '22');
    mobileFlag.style.cssText = 'border-radius:2px;box-shadow:0 0 0 1px rgba(0,0,0,0.15);display:block;';
    mobileBtn.appendChild(mobileFlag);

    var arrow = document.createElement('span');
    arrow.className = 'lang-mobile-arrow';
    arrow.setAttribute('aria-hidden', 'true');
    arrow.textContent = '\u25be';   // ▾
    mobileBtn.appendChild(arrow);

    // Pannello a discesa
    var dropdown = document.createElement('div');
    dropdown.className = 'lang-dropdown';
    dropdown.id = 'langDropdown';
    dropdown.setAttribute('hidden', '');

    Object.keys(LANGS).forEach(function (code) {
      var item = document.createElement('button');
      item.className = 'lang-dropdown-item';
      item.setAttribute('type', 'button');
      item.setAttribute('data-lang-item', code);
      item.appendChild(makeFlagImg(code, 32, 22));
      item.appendChild(document.createTextNode('\u00a0' + LANGS[code].label));
      item.addEventListener('click', function (e) {
        e.stopPropagation();
        apply(code);
        closeDropdown();
      });
      dropdown.appendChild(item);
    });

    function openDropdown() {
      dropdown.removeAttribute('hidden');
      mobileBtn.setAttribute('aria-expanded', 'true');
    }
    function closeDropdown() {
      dropdown.setAttribute('hidden', '');
      mobileBtn.setAttribute('aria-expanded', 'false');
    }

    mobileBtn.addEventListener('click', function (e) {
      e.stopPropagation();
      if (mobileBtn.getAttribute('aria-expanded') === 'true') {
        closeDropdown();
      } else {
        openDropdown();
      }
    });

    // Chiude se si tocca fuori
    document.addEventListener('click', function () { closeDropdown(); });

    switcher.appendChild(mobileBtn);

    // Il dropdown va nel logo-bar (che ha position:sticky/relative)
    var logoBar = switcher.closest('.logo-bar') || document.body;
    logoBar.appendChild(dropdown);

    // Salva riferimenti per aggiornare flag e stato attivo
    switcher._mobileFlag = mobileFlag;
    switcher._dropdown = dropdown;
  }

  function init() {
    buildSwitcher();
    apply(currentLang);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

}());
